services:
  preprocessor:
    build:
      context: ../
      dockerfile: infra/docker/dockerfile-preprocessor
    image: observer:0.9
    environment:
      - PYTHONPATH=/workspace/src
    volumes:
      - ${DATA_DIR}:/workspace/data
      - ${SRC_DIR}:/workspace/src
      - ./entrypoint-preprocessor.sh:/workspace/entrypoint.sh
    user: "${UID}:${GID}"
    shm_size: '${SHARED_MEMORY}'
    working_dir: /workspace
    stdin_open: true
    entrypoint: ["bash", "entrypoint.sh"]

  trainer:
    build:
      context: ../
      dockerfile: infra/docker/dockerfile-trainer
    image: trainer:0.9
    environment:
      - PYTHONPATH=/workspace/src
      - TORCH_HOME=/workspace/.torch_cache
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
    volumes:
      # - ${TORCH_CACHE_DIR}:/workspace/.torch_cache
      - ${DATA_DIR}:/workspace/data
      - ${SRC_DIR}:/workspace/src
      - ${MODELS_DIR}:/workspace/models
      - ${PREDICTIONS_DIR}:/workspace/predictions
      - ${RESULTS_DIR}:/workspace/results
      - ./entrypoint-trainer.sh:/workspace/entrypoint.sh
    user: "${UID}:${GID}"
    shm_size: '${SHARED_MEMORY}'
    working_dir: /workspace
    stdin_open: true
    runtime: nvidia
    entrypoint: ["bash", "entrypoint.sh"]